### ISSUE TITLE
[JOSS Review] shapelets-test command fails, missing `tests/` folder?

### ISSUE THREAD

**Issue by tbmiller-astro** [uw-comphys/shapelets#16]
Hello all,

Starting my initial review for the JOSS submission. Everything seems to have installed correctly but following the readme I attempted to run the `shapelets-test` command which failed, it seems there is a `tests/` folder missing? I'll attach the full trace below.

```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/shaplets/bin/shapelets-test", line 8, in <module>
    sys.exit(run_tests())
  File "/Users/timothymiller/Documents/research/packages/shapelets/shapelets/shapelets/entry_points.py", line 80, in run_tests
    os.chdir("tests/")
FileNotFoundError: [Errno 2] No such file or directory: 'tests/' 
```

Automated tests are part of the JOSS criterion, so some will need to be added but it seems the infrastructure is there so maybe just the folder is missing?

**Comment by mptino** [comment]
Thanks for the issue - the unit test framework was implemented (i.e. entry point support) but the unit tests themselves are still largely in development... 

I have uploaded a minimal set of unit tests (testing the various shapelet function definitions in `shapelets.functions` and the basic functionality of the `shapelets.self_assembly` sub-module). This now allows for functionality of the `shapelets_test`  entry point.

More unit tests will appear in the coming few weeks.

**Comment by mptino** [comment]
More unit tests for the `self_assembly` submodule have been added with PR #22. 

Unit tests for the `astronomy` submodule are near completion and should be uploaded within the next week.

**Comment by nasserma** [comment]
@tbmiller-astro we have committed the last set of unit tests and consider this issue resolved, could you please confirm.

**Comment by tbmiller-astro** [comment]
Thanks for adding these in, happy to mark this as completed now.
