### ISSUE TITLE
[JOSS Review] Missing API documentation

### ISSUE THREAD

**Issue by tbmiller-astro** [uw-comphys/shapelets#17]
Hello again,

Just went through all of the examples and they appeared to work well. The description of all of the examples in the paper and the `examples/` folder is really nice. 

One thing that is missing is API documentation of all the functionality of the package. I see all of the code itself is well documented so it should be relatively easy to put together using automated packages like [pdoc](https://pdoc.dev) or [sphinx](https://www.sphinx-doc.org/en/master/index.html).

**Comment by nasserma** [comment]
@tbmiller-astro we have created documentation using pdoc which is now linked from the README of the repository. For your convenience, you can also access it [here](https://uw-comphys.github.io/shapelets/). We think that this resolve this issue, please confirm and we will close it.

**Comment by tbmiller-astro** [comment]
The docs look great!
