### ISSUE TITLE
Shapelets PyPI Entry Issues

### ISSUE THREAD

**Issue by mptino** [uw-comphys/shapelets#44]
Two issues for the shapelets PyPI entry have been found:

1. The information available for this library on libraries.io (https://libraries.io/pypi/shapelets) contains outdated information from the previous shapelets package. Specifically, this includes the *Documentation* section, as well as the *Homepage* link near the top of the page. 
2. Note that pip only installs the shapelets/shapelets/ directory after using `pip install shapelets`. However, after doing this command, the installed directory **does not match** the shapelets/shapelets/ directory from the 1.0 release distributions found on GitHub. Similarly, the distributions provided on PyPI (under *Download files*, the .whl and tarball distributions) do not match the shapelets/shapelets/ 1.0 release distributions found on GitHub.

**Comment by nasserma** [comment]
Item #2 should be resolved, please confirm, item #1 is not something that I am sure how to resolve. The actual PyPI entry is correct and up-to-date,

https://pypi.org/project/shapelets/

I am not sure what the relevance/importance of libraries.io is.

**Comment by mptino** [comment]
Item # 2 is resolved, but an empty discrete_transform/ directory is still apparent upon installation. This however does not affect the installation or package functionality.

Agreed that # 1 is not of particular importance, as the PyPI entry is correct and up-to-date.
