### ISSUE TITLE
Test entry point using hardcoded python

### ISSUE THREAD

**Issue by Alex-Vasile** [uw-comphys/shapelets#46]
The current entry point for the tests hardcodes python or python3 into the run script. This causes issues on systems with multiple python interpreters installed. For example on a Mac if I have both Python@3.11 and Python@3.12 installed through brew, Python@3.12 is symlinked to `python3` while Python@3.11 is symlinked to `python3.11`. If I install `shapelets` using my Python@3.11 `pip` I cannot use the `shapelets-test` command since it will try to run with `python3` which is Python@3.12.

https://github.com/uw-comphys/shapelets/blob/cd45ff9174503c44179538af2d83cf2c2444d53a/shapelets/_entry_points.py#L61C5-L64C48

**Comment by mptino** [comment]
This bug is fixed with commit #47
